//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemWatcherApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemWatcherApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has been created {1}.
        /// </summary>
        internal static string File_Has_Been_Created {
            get {
                return ResourceManager.GetString("File_Has_Been_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rule matched..
        /// </summary>
        internal static string No_Rule_Matched {
            get {
                return ResourceManager.GetString("No_Rule_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Ctrl+C&apos; or &apos;Ctrl+Break&apos; to quit the app..
        /// </summary>
        internal static string Suggesting_The_Way_To_Quit {
            get {
                return ResourceManager.GetString("Suggesting_The_Way_To_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been moved to {0}.
        /// </summary>
        internal static string The_File_Has_Been_Moved_To {
            get {
                return ResourceManager.GetString("The_File_Has_Been_Moved_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule &quot;{0}&quot; was matched..
        /// </summary>
        internal static string The_Rule_Was_Matched {
            get {
                return ResourceManager.GetString("The_Rule_Was_Matched", resourceCulture);
            }
        }
    }
}
